### ISSUE TITLE
Many (near)duplicate records in the JSON files

### ISSUE THREAD

**Issue by xrotwang** [cldf-datasets/imtvault#2]
There are many (535, based on `ID`) near-duplicates in the JSON data in `extracted_examples`, e.g.
https://github.com/langsci/imtvault/blob/a5000d9da6ca27cd1d34655bd283498a4276fbb7/extracted_examples/store-78-06examples.json#L2-L23
and
https://github.com/langsci/imtvault/blob/a5000d9da6ca27cd1d34655bd283498a4276fbb7/extracted_examples/store-78-06examples.json#L118-L139
(The only difference in this case being the footnote content added in one translation.)

**Comment by Glottotopia** [comment]
The example itself is present in the original book three times in chapter 6 ((1), (41), and (61)). The question is how to establish which near-duplicates are near enough to merge them. Very often, linguists use minimal pairs to illustrate some contrast, so Levenshtein or other distance measures are not useful.

The Papuan Malay grammar has the additional problem of multiple `\gll`s for one `\glt`

```\ea
\label{Example_6.61}
\gll {\ldots} {tida} {perna} {dia} {liat,} {[\bluebold{ko}]} {[\bluebold{sungay}} {\bluebold{ko}]} {bisa} {terbuka}\\ %
{  }   \textsc{neg}  once  \textsc{3sg}  see  \textsc{2sg}  river  \textsc{2sg}  be.able  be.opened\\
\gll {begini}\\
 {like.this}\\
\glt
[Seeing the ocean for the first time:] ‘[never before has he seen, what, a river that is so very big like this ocean,] never before has he seen \bluebold{you, you river} can be wide like this?’ \textstyleExampleSource{[080922-010a-CvNF.0212-0213]}
```
In cases like the one above, only the last `\gll` gets picked up for src and imt, which is *begini* 'like.this'. Obviously, this does not match the translation. It might be necessary to exclude books which show this pattern.

**Comment by xrotwang** [comment]
What I'm doing at the moment is picking the first example per unique ID. This means that I'm missing potential extra information in 535 cases - out of ~41,000. Maybe this potential loss in <1% of the examples is acceptable after all.

**Comment by Glottotopia** [comment]
OK, I  had missed that the ID was the same. The ID includes a hash of the source line. Same source line, same ID. This takes care of the fact that some authors repeat examples, which we do not want. But indeed, the export should strip the repeated IDs.

**Comment by xrotwang** [comment]
Btw. a nice side effect of the CLDF dataset (plus the `cldfviz` package): We could easily include stuff like this in the repos README.md:
![map](https://user-images.githubusercontent.com/870184/160350468-5cf946ee-82c7-4615-9428-23ff8db65d62.jpg)

**Comment by xrotwang** [comment]
Also btw.: This IGT collection is a perfect set to get the `pyigt` battle-tested.

**Comment by Glottotopia** [comment]
could the colour dimension use a logarithmic scale? Japhug's 3000 examples now basically mean that everything else is in shades of dark violet

**Comment by xrotwang** [comment]
Ah, right. I guess I could just also compute log(count) and just plot that.

**Comment by xrotwang** [comment]
![Uploading map.jpg…]()

**Comment by Glottotopia** [comment]
The scale now seems to be the natural logarithm. The colour spread is much better. I wonder, though, how many people can make sense of e^8.1.
